### PR TITLE
Add Local Storage functionality to preserve form data

### PR DESCRIPTION
**Pull request by Zafron047**
Please review the code changes and ensure that the Local Storage implementation follows best practices and doesn't introduce any potential security or compatibility issues. Your feedback and suggestions for improvement are greatly appreciated.

> **Description**:

This pull request adds a new JavaScript function to preserve form data using the Local Storage feature. When the user interacts with the contact form, their input for the name, email, and message fields is stored in the Local Storage.

> **Changes Made:**

- Created a JavaScript function to handle form input changes and store the data in the Local Storage.
- Added event listener to the contact form to trigger the data preservation function.
- Implemented a separate function to retrieve and populate the form fields with the stored data from the Local Storage.
- Tested the functionality to ensure the form data is correctly preserved and retrieved.

> **Testing:**
- Tested the functionality in different browsers to ensure cross-browser compatibility.
- Checked that the form data is properly preserved and retrieved when reloading the page or navigating away from the form.

Best Regards,

[ Nohain Islam Zafron ]

### CODE REVIEW

**Review by taldr27 — COMMENTED** [review]
# Status: Invalidated 🔴
Hello team @Zafron047, @mutonic , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

I noticed that you submitted a pull request that doesn't include the previous review. Could you please submit the original pull request in your partner's repository, which includes the initial review? If you're unsure how to ask for a review, you can find helpful guidance in this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/how_to_ask_for_a_code_review.md).

image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready. 🙏

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit. gif_

**Comment by Zafron047** [comment]
Sir I do not quite understand the situation here. I have not submit any pr
before. How did I get an invalidation due to such reason.

Can you please enlighten me. I have tried to reach you in slack and also in
whatsapp.

**Comment by taldr27** [comment]
Hello @Zafron047, this is a pair programming activity, and you only need to implement the changes **in only one of the repositories**. Your group already submitted a [PR](https://github.com/mutonic/Portfolio_Microverse/pull/15) for the first review, which is why this PR is being invalidated and counted as a second review. It would be great if you could **submit your partner's repository for a re-review, incorporating the changes requested in the previous review**. Please check your Slack, I just replied there.

image

**Comment by Zafron047** [comment]
Understood. :'(

**Pull request merged**
